### ISSUE TITLE
Talking to the RPC via UDP? 

### ISSUE THREAD

**Issue by seivan** [apocolipse/Thrift-Swift#21]
Are there any plans on adding a UDP socket to talk to the RPC service?

**Comment by wyland** [comment]
You should be able to [configure the socket protocol here](https://github.com/apocolipse/Thrift-Swift/blob/7e8b84f28b099a1b9a750d03b8f7d2bddb0c5ec9/Sources/TSocketServer.swift#L52) using  `IPPROTO_UDP / SOCK_DGRAM` instead of `IPPROTO_TCP / SOCK_STREAM`.

If you can get this working, feel free to submit a pull request with some options on that server.

**Comment by seivan** [comment]
@wyland Sure, I'll be implementing the service first to have something to try against. 
One concern is that UDP doesn't work that well on iOS devices as the hardware might sleep, I am trying to figure out how to wake it up. Apple docs recommends not to go with low level POSIX code and instead using CFSocket which you guys seem to be doing, I am just trying to wrap my head around how to kickstart the device to start sending the packages. Do you got any experience with UDP on iOS - or more specifically, UDP across cellular connections?

**Comment by seivan** [comment]
Another note, I am wondering if it were to be a better solution to "outsource" the socket stuff to a third party library like [IBM/BlueSocket](https://github.com/IBM-Swift/BlueSocket).

**Comment by wyland** [comment]
Unfortunately we rely on TCP and don't have any personal experience using UDP.  As long as you conform to `TTransport`, I don't believe you will run into any issues using a third party like BlueSocket as your client to a thrift service.
